static_resources:
  listeners:
  - address:
     socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          access_log:
            name: envoy.file_access_log
            config:
              path: /tmp/access.log
          stat_prefix: grpc_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: jetty-unix
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: jetty-unix
    connect_timeout: 1s
    type: static
    lb_policy: round_robin
    hosts:
    - pipe:
        path: /tmp/jetty.sock
admin:
  access_log_path: '/dev/null'
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9091
